# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "shonansurvivors-master-tfstate"
    encrypt = true
    key     = "aws_organizations.tfstate"
    profile = "master"
    region  = "ap-northeast-1"
  }
}
