# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "shonansurvivors-prod-tfstate"
    key     = "foundation/network.tfstate"
    profile = "prod"
    region  = "ap-northeast-1"
  }
}
