# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "shonansurvivors-dev-tfstate"
    encrypt = true
    key     = "foundation/security_groups.tfstate"
    profile = "dev"
    region  = "ap-northeast-1"
  }
}
