# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "shonansurvivors-prod-tfstate"
    encrypt = true
    key     = "foundation/logs.tfstate"
    profile = "prod"
    region  = "ap-northeast-1"
  }
}
