name: Terraform CI

on:
  pull_request:
    paths:
      - '!**/README.md'
      - '!**/.gitignore'

jobs:
  ci:
    uses: shonansurvivors/github-actions-workflows/.github/workflows/terraform_ci.yml@main
    with:
      terraform_version: 1.1.2
      tflint_hcl_path: .tflint.hcl
