on:
  pull_request: # Todo: remove
  workflow_dispatch:

env:
  TFUPDATE_BASE_BRANCH: main
  TFUPDATE_BRANCH: tfupdate

jobs:
  setup-branch:
    runs-on: ubuntu-latest

    steps:
      - id: check-branch
        # NOTE: Shows lots of warnings because of https://github.com/octokit/request-action#warnings
        uses: octokit/request-action@v2.0.18
        with:
          route: GET /repos/:repository/git/ref/:ref
          repository: ${{ github.repository }}
          ref: heads/${{ env.TFUPDATE_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - uses: actions/checkout@v2
        if: steps.check-branch.outputs.status == 200
        with:
          ref: ${{ env.TFUPDATE_BRANCH }}

      - uses: actions/checkout@v2
        if: steps.check-branch.outputs.status != 200
        with:
          ref: ${{ env.TFUPDATE_BASE_BRANCH }}

      - name: Create tfupdate branch if not exist
        if: steps.check-branch.outputs.status != 200
        run: |
          git branch ${{ env.TFUPDATE_BRANCH }}
          git branch --set-upstream-to=origin/${{ env.TFUPDATE_BASE_BRANCH }} ${{ env.TFUPDATE_BRANCH }}

      - name: Get the commit sha before tfupdate
        id: before-sha
        run: |
          echo ::set-output name=sha::$(git log --pretty=%H | head -n1)

#    jobs:
#      tfupdate-provider:
#        runs-on: ubuntu-latest
#
#        env:
#          TFUPDATE_PROVIDER: hashicorp/aws
#          TF_KIND: aws
#          TF_DIR: ./envs/master/ops
#
#      steps:
#      - name: (${{ env.TF_KIND }}) tfupdate release latest -s tfregistryProvider ${{ env.TFUPDATE_PROVIDER }} .
#        id: get-latest-version
#        run: |
#          cd ${TF_DIR}
#          echo ::set-output name=version::$(tfupdate release latest -s tfregistryProvider ${TFUPDATE_PROVIDER})
#
#      - name: (${{ env.TF_KIND }}) tfupdate provider ${{ env.TFUPDATE_PROVIDER }} .
#        run: |
#          cd ${TF_DIR}
#          tfupdate provider ${TFUPDATE_PROVIDER} -v ${{ steps.get-latest-version.outputs.version }} .
#
#      - uses: EndBug/add-and-commit@v7
#        with:
#          branch: ${{ env.TFUPDATE_BRANCH }}
#          message: "Update terraform/${{ env.TF_KIND }}: tfupdate provider ${{ env.TFUPDATE_PROVIDER }} ."
#
#      - name: Get the commit sha after tfupdate
#        id: after-sha
#        run: |
#          echo ::set-output name=sha::$(git log --pretty=%H | head -n1)
