name: tfupdate

on:
  pull_request: # Todo: remove
  workflow_dispatch:

env:
  TFUPDATE_BINARY: https://github.com/minamijoyo/tfupdate/releases/download/v0.6.3/tfupdate_0.6.3_linux_amd64.tar.gz
  TFUPDATE_BASE_BRANCH: main
  TFUPDATE_BRANCH: tfupdate

jobs:
  set-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.value }}

    steps:
      - uses: actions/checkout@v2

      - id: set-matrix
        run: |
          dirs=$(find envs/master -type f -name '*.tf' -exec dirname {} \; | grep -v '_templates\|modules\|\.terraform' | uniq |  jq -R -s -c 'split("\n")[:-1]')
          echo $dirs
          echo "::set-output name=value::${dirs}"

  provider:
    needs: set-matrix

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        tfupdate: ${{ fromJson(needs.set-matrix.outputs.matrix) }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TFUPDATE_PROVIDER: aws
      TF_KIND: aws
      TF_DIR: ${{ matrix.tfupdate.DIR }}

    steps:
      - id: check-branch
        # NOTE: Shows lots of warnings because of https://github.com/octokit/request-action#warnings
        uses: octokit/request-action@v2.0.18
        with:
          route: GET /repos/:repository/git/ref/:ref
          repository: ${{ github.repository }}
          ref: heads/${{ env.TFUPDATE_BRANCH }}
        continue-on-error: true

      - uses: actions/checkout@v2
        if: steps.check-branch.outputs.status == 200
        with:
          ref: ${{ env.TFUPDATE_BRANCH }}

      - uses: actions/checkout@v2
        if: steps.check-branch.outputs.status != 200
        with:
          ref: ${{ env.TFUPDATE_BASE_BRANCH }}

      - name: Create tfupdate branch if not exist
        if: steps.check-branch.outputs.status != 200
        run: |
          git branch ${{ env.TFUPDATE_BRANCH }}
          git branch --set-upstream-to=origin/${{ env.TFUPDATE_BASE_BRANCH }} ${{ env.TFUPDATE_BRANCH }}

      - name: Get the commit sha before tfupdate
        id: before-sha
        run: |
          echo ::set-output name=sha::$(git log --pretty=%H | head -n1)

      - name: Setup tfupdate from binary
        run: |
          set -o pipefail
          wget -P /tmp ${TFUPDATE_BINARY}
          basename ${TFUPDATE_BINARY} | xargs -I {} tar xvf /tmp/{} -C /tmp
          sudo mv /tmp/tfupdate /usr/local/bin
          sudo chmod +x /usr/local/bin/tfupdate

      - name: (${{ env.TF_KIND }}) tfupdate provider ${{ env.TFUPDATE_PROVIDER }} .
        run: |
          cd ${TF_DIR}
          tfupdate provider ${TFUPDATE_PROVIDER} .

      - uses: EndBug/add-and-commit@v7
        with:
          branch: ${{ env.TFUPDATE_BRANCH }}
          message: "Update terraform/${{ env.TF_KIND }}: tfupdate provider ${{ env.TFUPDATE_PROVIDER }} ."

      - name: Get the commit sha after tfupdate
        id: after-sha
        run: |
          echo ::set-output name=sha::$(git log --pretty=%H | head -n1)

      - uses: repo-sync/pull-request@v2
        # if: ${{ steps.before-sha.outputs.sha != steps.after-sha.outputs.sha }}
        with:
          source_branch: ${{ env.TFUPDATE_BRANCH }}
          destination_branch: ${{ env.TFUPDATE_BASE_BRANCH }}
          pr_title: Update Terraform Version & Terraform Providers Version
          pr_body: |
            **This pull request is created automatically by the CI: [tfupdate](https://github.com/${{ github.repository }}/actions?query=workflow%3Atfupdate)**

            ---

            Run the below code to try this changes locally.

            \`\`\`
            cd path/to/${{ github.repository }}
            gh pr checkout ${{ env.TFUPDATE_BRANCH }}
            \`\`\`
          pr_label: tfupdate
          pr_allow_empty: false
